### ISSUE TITLE
Connection to fm-dx-webserver interrupted

### ISSUE THREAD

**Issue by DK1MAX** [Highpoint2000/webserver-scanner#4]
Using this plugin with latest version (1.3.1) of fm-dx-webserver results in an an endless connected/not connected loop on firefox browser trying to use my fm-dx-webserver. OS: Ubuntu Server 24.04.1 LTS.

Seems to be an issue from fm-dx-webserver 1.3.1 as the plugin 2.6a shows same behaviour.

**Comment by Highpoint2000** [comment]
Hallo Max,
  

  
Hast Du die neuste Version heruntergeladen? Hat das System Zugriff auf den neuen plugin_config Ordner in dem die config liegt? Bei mir unter Windows u.a. auch Linux läuft der Scanner.
  

  
73, Jens
  

  

  

  
  
  
  
  
>

**Comment by DK1MAX** [comment]
Hallo Jens,

der Ordner plugins_configs wurde nicht erstellt, deshalb der Fehler. Ich versuche das manuell und werde berichten.

[04:42] [INFO] Plugin LiveMap 1.1 initialized successfully.
[04:42] [INFO] Plugin RDS-Logger Plugin 1.6a initialized successfully.
[04:42] [INFO] Plugin Scanner Plugin 2.6c BETA initialized successfully.
[04:42] [INFO] Plugin Signal Meter Small 1.2.2 initialized successfully.
[04:42] [INFO] Plugin Station Logo Plugin 3.3a initialized successfully.
[04:42] [INFO] Plugin Current weather 1.2 initialized successfully.
[04:42] [INFO] -----------------------------------------------------------------
[04:42] [INFO] Plugin scanner_server loaded successfully!
[04:42] [INFO] Scanner configuration not found. Creating scanner.json.
node:internal/fs/utils:351
    throw err;
    ^

**Error: ENOENT: no such file or directory, open '/home/fmdx/build/fm-dx-webserver/plugins_configs/scanner.json'**
    at Object.openSync (node:fs:596:3)
    at Object.writeFileSync (node:fs:2322:35)
    at loadConfig (/home/fmdx/build/fm-dx-webserver/plugins/Scanner/scanner_server.js:94:8)
    at Object.<anonymous> (/home/fmdx/build/fm-dx-webserver/plugins/Scanner/scanner_server.js:100:22)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/fmdx/build/fm-dx-webserver/plugins_configs/scanner.json'
}

Node.js v18.19.1
fmdx@jn58st:~/build/fm-dx-webserver$

**Comment by DK1MAX** [comment]
Problem solved. After creating the /home/fmdx/build/fm-dx-webserver/plugins_configs folder manually everything went smooth.
DANKE für die Hilfe und gut DX!

73... Max. DK1MAX.
